#!/bin/bash

USERADD="/usr/sbin/useradd"
ID="/usr/bin/id"
BASEDIR="/usr/local/var/run"
MKDIR="/bin/mkdir -p"
ENABLE_BGPMONUSER="yes"

if [ ${ENABLE_BGPMONUSER} == "no" ]
then
  exit
fi
 
if [ ${USERADD} = no ]
then
  USERADD=`which useradd`
  if [ $? = 1 ]
  then
    echo "Unable to add user: bgpmon"
    exit 1
  fi
fi
${ID} bgpmon > /dev/null 2>&1
if [ $? = 1 ]
then
  ${MKDIR} ${BASEDIR}
  ${USERADD} -c "BGPmon Account" -r -b ${BASEDIR} bgpmon
fi
